# Generated by Django 4.1.7 on 2023-06-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=40)),
                ('product_count', models.IntegerField(blank=True)),
                ('product_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20)),
                ('cart_info', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.cartdata')),
            ],
        ),
    ]
