# Generated by Django 4.1.7 on 2023-06-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cartdata_cart_data_name_alter_cartdata_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdata',
            name='product_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='cartdata',
            name='product_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cartdata',
            name='product_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
