# Generated by Django 4.1.7 on 2023-06-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_cartdata_product_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=40, null=True)),
                ('product_count', models.IntegerField(blank=True, default=1)),
                ('product_price', models.FloatField(blank=True, default=0, null=True)),
                ('cart_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_info',
        ),
        migrations.DeleteModel(
            name='CartData',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.cart'),
        ),
    ]
