# Generated by Django 4.1.7 on 2023-06-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0013_alter_category_parent'),
        ('Cart', '0005_order_remove_cart_cart_info_delete_cartdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Catalog.product'),
        ),
    ]
