# Generated by Django 4.1.7 on 2023-06-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0013_alter_category_parent'),
        ('Cart', '0006_alter_order_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalog.product'),
        ),
    ]
