# Generated by Django 4.1.7 on 2023-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_customuser_birth_date_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, default=' ', null=True),
        ),
    ]
