# Generated by Django 4.1.7 on 2023-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0007_customuser_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Женщина'), ('M', 'Мужчина')], default='', max_length=20),
        ),
    ]
