# Generated by Django 4.1.7 on 2023-06-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_cart_info'),
        ('Person', '0016_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.cart'),
        ),
    ]
