# Generated by Django 4.1.7 on 2023-03-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='Catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Catalog.mark'),
        ),
    ]
