# Generated by Django 4.1.7 on 2023-06-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_remove_product_category_rename_category_maincategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='childCategory',
            field=models.ManyToManyField(related_name='childCategory', to='Catalog.childcategory'),
        ),
    ]
