# Generated by Django 4.1.7 on 2023-06-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_remove_childcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='childCategory',
            field=models.ManyToManyField(to='Catalog.childcategory'),
        ),
    ]
