# Generated by Django 4.1.7 on 2023-06-28 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0010_remove_maincategory_childcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(default=' ', null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Catalog.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='childcategory',
            name='mainCat',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Catalog.category'),
        ),
        migrations.DeleteModel(
            name='ChildCategory',
        ),
    ]
